#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom &
dunst &
gromit-mpx &
feh --bg-fill ~/Downloads/nologo.jpg
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI

bspc config border_width         0
bspc config window_gap           10
bspc config top_padding          0

bspc config split_ratio          0.52
# bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config active_border_color  \#00008b

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
